### ISSUE TITLE
Problem when reading SCPH1001 BIOS

### ISSUE THREAD

**Issue by RoDeLoPo** [beannaich/psxact#3]
Hi bennaich, awesome project you have! Unfortunately, coding an emulator is far beyond what I can handle, but I'd like to contribute to the project in any other way, if possible. I've compiled psxact on VS and tried running some images, but all of them were failing. I then ran the BIOS itself (not specifying an image), and sure enough, I got the same problem. The BIOS I'm using is SCPH1001, and it works fine with other emulators. Attached is a log file of the output. It would start outputting "Unknown Read", and would get stuck. I only left a few "Unknown Read" messages on the log file, since there were way to many. Is this a bug or could I be doing something wrong?

Log file: https://www.sendspace.com/file/nfu36x

**Comment by beannaich** [comment]
This emulator is still in the VERY early stages. Currently it'll get through about 17 MHz (~0.5 seconds) of the BIOS.

It seems that the BIOS does some very interesting things with the GPU to figure out versioning. The last thing I remember tracing was the CPU reading the GPU status register, then jumping to whatever the register returned.

Since I don't handle the GPU properly at all at this point, the emulator encounters this situation then crashes immediately. I was trying to figure out what a good value to return out of this was before I got sucked away to other projects.

**Comment by RoDeLoPo** [comment]
Sorry for the late reply! Hope you resume the project then, it would be really awesome!
